### ISSUE TITLE
Typecasting help

### ISSUE THREAD

**Issue by virtualalchemyb** [onlabsorg/swan-js#1]
Hello, 

First off all, amazing job on this package, it's perfect and so complete. I wish I could write something like this.

I have a little bit of trouble with the following:

```javascript
    const evaluate = swan.parse('company.year > 2000')
    const context = swan.createContext({company: {year: '2001'}})
    console.log({condition, answer: await evaluate(context)}) // answer is false
```

The input here is a string, which related to legacy code is hard to change to an integer / number.

Is there a possibility to cast the `company.year` type to number?

I looked at your buildins, but it appears that there is no casting from strings to numbers

**Comment by virtualalchemyb** [comment]
As an alternative, I can use the `Math` module to convert the type to a number, but I don't really understand how loading a module can be done. I read the docs here: https://github.com/onlabsorg/swan-js/blob/main/docs/modules/index.md, but can you maybe give me a code example of how to require a module?

**Comment by mdelbuono** [comment]
@virtualalchemyb , thanks for your contribution: it shows that the documentation is not clear enough. I'll try to improve it as soon as I have some free time.

Type casting is indeed available in the [text](https://github.com/onlabsorg/swan-js/blob/main/docs/modules/text.md) module, which you can load and use as follows in Swan:

```
text = require "text",
number = text.to_numb('123.45')
```

So your code should work if you modify it as follows:

```js
const evaluate = swan.parse(`
    (require 'text').to_numb(company.year) > 2000
`)
const context = swan.createContext({company: {year: '2001'}})
const answer = await evaluate(context)
```

The following part has nothing to do with your question, but since we are here, let me show you also a trick to split complex expressions such as `(require 'text').to_numb(company.year) > 2000` in a sequence of more simple expressions:

```js
const evaluate = swan.parse(`
   {
      text = require 'text',
      year = text.to_numb company.year,
      is_new_millennium = year > 2000
   }.is_new_millennium
`);
const context = swan.createContext({company: {year: '2001'}});
const answer = await evaluate(context);
```

**Comment by mdelbuono** [comment]
I'll close this, assuming my answer solved your issue.

**Comment by mdelbuono** [comment]
I'll close this, assuming my answer solved your issue.
